---
services:
  battleship-server:
    container_name: node
    restart: always
    pull_policy: build
    depends_on:
      - battleship-db
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - battleship-net
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      DEFAULT_ADMIN_USERNAME: "${DEFAULT_ADMIN_USERNAME}"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD}"
      JWT_EXPIRE: "${JWT_EXPIRE}"
      DB_URL: "${DB_URL}"

  battleship-db:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - battleship-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DB_NAME}"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  battleship-client:
    container_name: angular
    restart: always
    pull_policy: build
    depends_on:
      - battleship-server
    build:
      context: ./client/angular
      dockerfile: Dockerfile
    networks:
      - battleship-net
    ports:
      - 8081:80

networks:
  battleship-net:
