---
services:
  server:
    container_name: battleship-server
    hostname: battleship-server
    restart: always
    pull_policy: build
    build:
      context: ./server
      dockerfile: production.Dockerfile
    networks:
      - battleship-net
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      DEFAULT_ADMIN_USERNAME: "${DEFAULT_ADMIN_USERNAME}"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD}"
      JWT_EXPIRE: "${JWT_EXPIRE}"
      DB_URL: "${DB_URL}"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "battleship-net"
      traefik.http.services.battleship.loadbalancer.server.port: "8080"
      traefik.http.routers.battleship.rule: "Host(`battleship.davidevolpe.dev`) && PathPrefix(`/api`)"
      traefik.http.routers.battleship.entrypoints: "websecure"
      traefik.http.routers.battleship.tls: "true"
      traefik.http.routers.battleship.tls.certresolver: "production"

  client:
    container_name: battleship-client
    restart: always
    pull_policy: build
    depends_on:
      - server
    build:
      context: ./client/angular
      dockerfile: production.Dockerfile
    networks:
      - battleship-net
    environment:
      SERVER_URL: "${SERVER_URL}"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "battleship-net"
      traefik.http.services.battleship.loadbalancer.server.port: "80"
      traefik.http.routers.battleship.rule: "Host(`battleship.davidevolpe.dev`)"
      traefik.http.routers.battleship.entrypoints: "websecure"
      traefik.http.routers.battleship.tls: "true"
      traefik.http.routers.battleship.tls.certresolver: "production"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  battleship-net:
    name: battleship-net

