---
services:
  battleship-server:
    container_name: node
    restart: always
    depends_on:
      - battleship-db
    pull_policy: build
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - battleship-net
    environment:
      JWT_SECRET: test
      DEFAULT_ADMIN_USERNAME: test123
      DEFAULT_ADMIN_PASSWORD: test123
      JWT_EXPIRE: 1h
      DB_URL: mongodb://battleship:battleship@mongo:27017/Battleship

  battleship-db:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - battleship-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: battleship
      MONGO_INITDB_ROOT_PASSWORD: battleship
      MONGO_INITDB_DATABASE: Battleship
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./server/data:/data/db

  battleship-client:
    container_name: angular
    restart: always
    depends_on:
      - battleship-server
    pull_policy: build
    build:
      context: ./client/angular
      dockerfile: Dockerfile
    ports:
      - 8081:80
    networks:
      - battleship-net

networks:
  battleship-net:
